### ISSUE TITLE
Issue with scalaam-JS when using Scala 2.13.2

### ISSUE THREAD

**Issue by jevdplas** [acieroid/scala-am#14]
Scalaam-JS encounters following issue when using Scala 2.13.2
`Referring to non-existent class java.util.Locale`

Adding an extra dependency to the build.sbt file, as is commonly marked as the solution, does not work. (This dependency is still present in the build.sbt file.)

**Comment by noahvanes** [comment]
Note: the issue didn’t arise from updating to Scala 2.13.2, it was apparently already introduced yesterday when the parser issues were fixed using `java.util.Locale`, which is apparently not directly supported by Scala.js.

**Comment by jevdplas** [comment]
Note: the dependency has been placed in commented.

**Comment by noahvanes** [comment]
Fixed by removing the dependency on `java.util.Locale` (for which no up-to-date Scala.js library was available as an alternative) altogether.
