### ISSUE TITLE
Parse issue on test/gambit/compiler.scm

### ISSUE THREAD

**Issue by jevdplas** [acieroid/scala-am#16]
The Scheme parser cannot correctly parse the program test/gambit/compiler.scm.
The given error is the following: java.lang.NumberFormatException: For input string: "e1".
However, the given program does not contain numbers in scientific notation. On the other hand, the program contains variables called 'e1', and variable names ending in 'e1'. Hence, the parser seems to fail due to a wrong application of a parse rule.

**Comment by jevdplas** [comment]
Also fails on other benchmarks, such as test/WeiChenRompf2019/toplas98/dynamic.scm due to same reason.

**Comment by noahvanes** [comment]
The issue with identifiers being interpreted as floats was fixed in [`02b892c`](https://github.com/acieroid/scala-am/commit/02b892c7918081a5e1b0ca64e4857958366bf3c1), by ensuring that float literals can not start with the exponent.
