### ISSUE TITLE
Improve Scheme Parser

### ISSUE THREAD

**Issue by jevdplas** [acieroid/scala-am#9]
The current Scheme parser works well in most cases. However, there are some situations that occur reasonably frequently, which the Scheme parser still cannot handle. A prominent example is a file ending with a comment. In this case, a parser error will be thrown (`Error: could not fully parse expression`). In other cases (SCP1 benchmarks 3.3 and 5.21), the parser throws an error (`Error: right parenthesis expected`) even though the program is correct.

**Comment by jevdplas** [comment]
Additionally, the Scheme parser does not support all character literals. Character literals such as `#\space` and `#\newline`... are not supported.

**Comment by acieroid** [comment]
> Additionally, the Scheme parser does not support all character literals. Character literals such as `#\space` and `#\newline`... are not supported.

These are now supported (0d01fcb1), but all Scheme character literals shoul be supported.
